In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sim

In [2]:
seed = 54421
rng = np.random.default_rng(seed)
N = 1_000
results, XYZ = sim.sim(seed, N, save_edges=True, save_points=True)

np.mean(results["regular"])

np.float64(0.393)

In [3]:
results

,regular,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12
0,0,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(1, 5)","(0, 3)","(2, 3)","(4, 5)","(0, 2)","(2, 5)","(1, 3)","(3, 5)"
1,1,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(1, 5)","(0, 3)","(1, 4)","(2, 3)","(0, 2)","(4, 5)","(0, 5)","(3, 5)"
2,1,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(0, 3)","(1, 4)","(0, 2)","(4, 5)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"
3,0,"(0, 1)","(2, 4)","(0, 4)","(3, 4)","(0, 3)","(1, 4)","(0, 2)","(4, 5)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"
4,0,"(0, 1)","(2, 4)","(1, 2)","(0, 4)","(3, 4)","(0, 3)","(1, 4)","(4, 5)","(0, 2)","(0, 5)","(2, 5)","(1, 3)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(1, 5)","(0, 3)","(1, 4)","(2, 3)","(4, 5)","(0, 2)","(0, 5)","(3, 5)"
996,0,"(0, 1)","(1, 2)","(3, 4)","(1, 5)","(0, 3)","(1, 4)","(4, 5)","(0, 2)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"
997,0,"(0, 1)","(2, 4)","(1, 2)","(0, 4)","(3, 4)","(1, 5)","(0, 3)","(1, 4)","(4, 5)","(0, 5)","(2, 5)","(1, 3)"
998,0,"(0, 1)","(2, 4)","(1, 2)","(0, 4)","(1, 5)","(0, 3)","(1, 4)","(2, 3)","(0, 2)","(2, 5)","(1, 3)","(3, 5)"
999,0,"(0, 1)","(2, 4)","(0, 4)","(3, 4)","(0, 3)","(1, 4)","(2, 3)","(4, 5)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"

In [4]:
is_regular = results["regular"].astype(bool)
regs = results.loc[is_regular].head(3)
irregs = results.loc[~is_regular].head(3)
examples = pd.concat([regs, irregs])
display(examples)
display(examples.index)
display(XYZ[examples.index, :])

,regular,e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12
1,1,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(1, 5)","(0, 3)","(1, 4)","(2, 3)","(0, 2)","(4, 5)","(0, 5)","(3, 5)"
2,1,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(0, 3)","(1, 4)","(0, 2)","(4, 5)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"
5,1,"(0, 1)","(1, 2)","(0, 4)","(3, 4)","(1, 4)","(2, 3)","(0, 2)","(4, 5)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"
0,0,"(0, 1)","(2, 4)","(1, 2)","(3, 4)","(1, 5)","(0, 3)","(2, 3)","(4, 5)","(0, 2)","(2, 5)","(1, 3)","(3, 5)"
3,0,"(0, 1)","(2, 4)","(0, 4)","(3, 4)","(0, 3)","(1, 4)","(0, 2)","(4, 5)","(0, 5)","(2, 5)","(1, 3)","(3, 5)"
4,0,"(0, 1)","(2, 4)","(1, 2)","(0, 4)","(3, 4)","(0, 3)","(1, 4)","(4, 5)","(0, 2)","(0, 5)","(2, 5)","(1, 3)"

Index([1, 2, 5, 0, 3, 4], dtype='int64')

array([[ 0.24759781, -0.7676235 , -0.59114253, -0.13502802,  0.90549047,
        -0.40231137,  0.23069352,  0.87625126, -0.42304163,  0.99082895,
         0.13285241, -0.02466216,  0.64800179,  0.74792507, -0.14388108,
        -0.07559483, -0.91675136,  0.39224018],
       [ 0.60965706,  0.18575937,  0.7705918 ,  0.08261556,  0.02484628,
        -0.99627172, -0.17847734, -0.84883444, -0.49762027, -0.54230496,
         0.82089449,  0.1789904 , -0.71099269,  0.42304658, -0.56171255,
        -0.02683404, -0.36942131,  0.9288745 ],
       [-0.16109641, -0.20807619, -0.96475502, -0.90430152, -0.42609846,
        -0.02605501, -0.80688606, -0.32046132,  0.49622518,  0.04812573,
        -0.91126095,  0.40900783, -0.29091556, -0.73553351, -0.6118485 ,
         0.93825471,  0.28594477, -0.1947144 ],
       [ 0.34547314, -0.92755195,  0.14246296,  0.53895916,  0.48953518,
        -0.68547672,  0.36198656, -0.86208617,  0.35464513, -0.9741005 ,
        -0.13182703,  0.18371133, -0.73866926,  0.32166101,  0.59236975,
         0.1658951 ,  0.98197304, -0.09059668],
       [-0.01212231, -0.91124238, -0.4116921 , -0.65919857,  0.49860285,
        -0.56289648, -0.05990097, -0.96527584,  0.25427235,  0.31798561,
        -0.3599833 ,  0.87709587, -0.76213455, -0.58689224, -0.27332842,
         0.16814246, -0.6000579 ,  0.78208607],
       [-0.44148043,  0.80827209, -0.38960398, -0.2005674 ,  0.97051566,
         0.1336865 ,  0.22259553, -0.32443588,  0.91934356,  0.06030221,
         0.86656517, -0.49540735,  0.9555199 , -0.05487773, -0.28977605,
         0.5114771 , -0.84331284,  0.16496858]])

In [5]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

edge_traces = []
vertex_traces = []

for idx, row in examples.iterrows():
    xyz = XYZ[idx, :].reshape(6, 3)
    vertex_trace = go.Scatter3d(x = xyz[:, 0], y = xyz[:, 1], z = xyz[:, 2], text=[f"regular={is_regular[idx]}"]*6, mode="markers")
    xe, ye, ze = [], [], []
    for i, j in row[1:]:
        xe += [xyz[i, 0], xyz[j, 0], None]
        ye += [xyz[i, 1], xyz[j, 1], None]
        ze += [xyz[i, 2], xyz[j, 2], None]

    edge_trace = go.Scatter3d(
        x=xe,
        y=ye,
        z=ze,
        mode="lines",
        line=dict(width=4),
        name="Edges",
    )

    edge_traces.append(edge_trace)
    vertex_traces.append(vertex_trace)

fig = make_subplots(
    rows=3,
    cols=2,
    specs=[[{"type": "scene"}] * 2] * 3, 
    subplot_titles=["regular = True", "regular = False"] + 2 * 2 * [""],
    horizontal_spacing=0,
    vertical_spacing=0,
    column_widths=[1, 1],
    row_heights=[1]*3,
    
)

fig.update_layout(
    showlegend=False,
    autosize=False,
    width=1400,
    height=1000
)
fig.update_scenes(
    xaxis = dict(visible=False),
    yaxis = dict(visible=False),
    zaxis = dict(visible=False)
)

fig.print_grid()

for i, traces in enumerate(zip(edge_traces, vertex_traces)):
    fig.add_trace(traces[0], row=1 + i % 3, col=1 + i // 3)
    fig.add_trace(traces[1], row=1 + i % 3, col=1 + i // 3)


fig.show()

This is the format of your plot grid:
[ (1,1) scene  ]  [ (1,2) scene2 ]
[ (2,1) scene3 ]  [ (2,2) scene4 ]
[ (3,1) scene5 ]  [ (3,2) scene6 ]

In [6]:
from statsmodels.stats.proportion import proportion_confint
from scipy.stats import binomtest

r = pd.read_pickle(r"data\results__old")
alpha = 0.05

display(proportion_confint(np.sum(r["regular"]), len(r), alpha=alpha, method='beta'))
display(binomtest(np.sum(r["regular"]), len(r)).proportion_ci(confidence_level=0.95))
print(f"n={len(r)}")

FileNotFoundError: [Errno 2] No such file or directory: 'data\\results__old'